name: Build with CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env: 
  PICO_SDK_PATH: ../pico-sdk

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: sudo apt update && sudo apt install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential g++ libstdc++-arm-none-eabi-newlib
    - name: download sdk
      run: git clone --recurse-submodules https://github.com/raspberrypi/pico-sdk.git --branch master
    - name: run cmake configure
      run: cmake -DCMAKE_BUILD_TYPE=Release -S ./ -B ./build
    - name: run cmake build
      run: cmake --build ./build
    - name: store build output-files
      uses: actions/upload-artifact@v4
      with:
        name: cti_build
        path: |
         build/cti_*.elf*
         build/cti_*.uf2
